/**
 * Libreria esercizi BODYGROWTH — nome inglese + nome italiano.
 *
 * Catalogo curato a partire dai principali database di esercizi
 * (ExRx.net, Muscle & Strength, StrengthLog, JEFIT, free-exercise-db)
 * ed esteso oltre il bodybuilding: powerlifting, weightlifting olimpico,
 * strongman, kettlebell, calisthenics/street workout, functional/CrossFit,
 * cardio ed endurance, mobilità e stretching.
 */

export interface SeedExercise {
  name: string;
  nameIt: string;
  category: "COMPOUND" | "ISOLATION" | "CARDIO" | "STRETCHING";
  muscleGroups: string[];
  primaryMuscle: string;
  equipment: string[];
  difficulty: number;
  aliases: string[];
}

const e = (
  name: string,
  nameIt: string,
  category: SeedExercise["category"],
  muscleGroups: string[],
  primaryMuscle: string,
  equipment: string[],
  difficulty = 3,
  aliases: string[] = []
): SeedExercise => ({ name, nameIt, category, muscleGroups, primaryMuscle, equipment, difficulty, aliases });

export const exerciseLibrary: SeedExercise[] = [
  // ─── PETTORALI ──────────────────────────────────────────────────────────────
  e("Barbell Bench Press", "Panca piana con bilanciere", "COMPOUND", ["CHEST", "TRICEPS", "SHOULDERS"], "CHEST", ["BARBELL"], 3, ["bench press", "panca piana", "distensioni su panca"]),
  e("Incline Barbell Bench Press", "Panca inclinata con bilanciere", "COMPOUND", ["CHEST", "TRICEPS", "SHOULDERS"], "CHEST", ["BARBELL"], 3, ["incline bench", "panca inclinata"]),
  e("Decline Barbell Bench Press", "Panca declinata con bilanciere", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["BARBELL"], 3, ["panca declinata"]),
  e("Wide-Grip Bench Press", "Panca piana presa larga", "COMPOUND", ["CHEST", "TRICEPS", "SHOULDERS"], "CHEST", ["BARBELL"], 3),
  e("Guillotine Press", "Panca ghigliottina", "COMPOUND", ["CHEST", "SHOULDERS"], "CHEST", ["BARBELL"], 4),
  e("Barbell Floor Press", "Floor press con bilanciere", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["BARBELL"], 3),
  e("Dumbbell Bench Press", "Panca piana con manubri", "COMPOUND", ["CHEST", "TRICEPS", "SHOULDERS"], "CHEST", ["DUMBBELL"], 2, ["db bench press", "manubri piana"]),
  e("Incline Dumbbell Press", "Panca inclinata con manubri", "COMPOUND", ["CHEST", "TRICEPS", "SHOULDERS"], "CHEST", ["DUMBBELL"], 2, ["manubri inclinata"]),
  e("Decline Dumbbell Press", "Panca declinata con manubri", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["DUMBBELL"], 2),
  e("Neutral-Grip Dumbbell Press", "Panca con manubri presa neutra", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["DUMBBELL"], 2, ["hammer grip press"]),
  e("Dumbbell Floor Press", "Floor press con manubri", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["DUMBBELL"], 2),
  e("Machine Chest Press", "Chest press alla macchina", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["MACHINE"], 1, ["pectoral press"]),
  e("Incline Machine Press", "Chest press inclinata alla macchina", "COMPOUND", ["CHEST", "SHOULDERS"], "CHEST", ["MACHINE"], 1),
  e("Decline Machine Press", "Chest press declinata alla macchina", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["MACHINE"], 1),
  e("Smith Machine Bench Press", "Panca piana allo Smith", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["SMITH_MACHINE"], 2),
  e("Smith Machine Incline Press", "Panca inclinata allo Smith", "COMPOUND", ["CHEST", "SHOULDERS"], "CHEST", ["SMITH_MACHINE"], 2),
  e("Cable Chest Press", "Chest press ai cavi", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["CABLE"], 2),
  e("Push-Up", "Piegamenti sulle braccia", "COMPOUND", ["CHEST", "TRICEPS", "CORE"], "CHEST", ["BODYWEIGHT"], 1, ["pushup", "flessioni"]),
  e("Weighted Push-Up", "Piegamenti zavorrati", "COMPOUND", ["CHEST", "TRICEPS", "CORE"], "CHEST", ["BODYWEIGHT"], 3),
  e("Incline Push-Up", "Piegamenti su rialzo", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["BODYWEIGHT"], 1),
  e("Decline Push-Up", "Piegamenti con piedi rialzati", "COMPOUND", ["CHEST", "SHOULDERS", "TRICEPS"], "CHEST", ["BODYWEIGHT"], 2),
  e("Wide-Grip Push-Up", "Piegamenti presa larga", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["BODYWEIGHT"], 1),
  e("Archer Push-Up", "Piegamenti arciere", "COMPOUND", ["CHEST", "TRICEPS", "CORE"], "CHEST", ["BODYWEIGHT"], 4),
  e("One-Arm Push-Up", "Piegamenti a un braccio", "COMPOUND", ["CHEST", "TRICEPS", "CORE"], "CHEST", ["BODYWEIGHT"], 5),
  e("Plyometric Push-Up", "Piegamenti pliometrici", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["BODYWEIGHT"], 4, ["clap push-up"]),
  e("Ring Push-Up", "Piegamenti agli anelli", "COMPOUND", ["CHEST", "TRICEPS", "CORE"], "CHEST", ["BODYWEIGHT"], 3),
  e("Pseudo Planche Push-Up", "Piegamenti pseudo planche", "COMPOUND", ["CHEST", "SHOULDERS", "CORE"], "CHEST", ["BODYWEIGHT"], 4),
  e("Chest Dip", "Dip alle parallele per pettorali", "COMPOUND", ["CHEST", "TRICEPS", "SHOULDERS"], "CHEST", ["BODYWEIGHT"], 3, ["dips", "parallele"]),
  e("Weighted Chest Dip", "Dip zavorrati per pettorali", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["BODYWEIGHT"], 4),
  e("Assisted Dip Machine", "Dip assistiti alla macchina", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["MACHINE"], 1),
  e("Cable Fly", "Croci ai cavi", "ISOLATION", ["CHEST"], "CHEST", ["CABLE"], 2, ["cable crossover"]),
  e("Low Cable Fly", "Croci ai cavi dal basso", "ISOLATION", ["CHEST"], "CHEST", ["CABLE"], 2),
  e("High Cable Fly", "Croci ai cavi dall'alto", "ISOLATION", ["CHEST"], "CHEST", ["CABLE"], 2),
  e("Single-Arm Cable Fly", "Croci ai cavi monobraccio", "ISOLATION", ["CHEST"], "CHEST", ["CABLE"], 2),
  e("Dumbbell Fly", "Croci con manubri", "ISOLATION", ["CHEST"], "CHEST", ["DUMBBELL"], 2, ["croci su panca"]),
  e("Incline Dumbbell Fly", "Croci su panca inclinata", "ISOLATION", ["CHEST"], "CHEST", ["DUMBBELL"], 2),
  e("Decline Dumbbell Fly", "Croci su panca declinata", "ISOLATION", ["CHEST"], "CHEST", ["DUMBBELL"], 2),
  e("Pec Deck", "Pectoral machine (farfalla)", "ISOLATION", ["CHEST"], "CHEST", ["MACHINE"], 1, ["butterfly", "farfalla"]),
  e("Dumbbell Pullover", "Pullover con manubrio", "ISOLATION", ["CHEST", "BACK"], "CHEST", ["DUMBBELL"], 2),
  e("Barbell Pullover", "Pullover con bilanciere", "ISOLATION", ["CHEST", "BACK"], "CHEST", ["BARBELL"], 3),
  e("Svend Press", "Svend press", "ISOLATION", ["CHEST"], "CHEST", ["OTHER"], 1, ["plate press"]),
  e("Landmine Press", "Landmine press", "COMPOUND", ["CHEST", "SHOULDERS", "CORE"], "CHEST", ["BARBELL"], 2),
  e("Band Chest Press", "Spinte con elastico", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["BANDS"], 1),
  e("Band Chest Fly", "Croci con elastico", "ISOLATION", ["CHEST"], "CHEST", ["BANDS"], 1),
  e("Medicine Ball Chest Pass", "Passaggio con palla medica", "COMPOUND", ["CHEST", "TRICEPS"], "CHEST", ["OTHER"], 2),

  // ─── DORSO / SCHIENA ────────────────────────────────────────────────────────
  e("Deadlift", "Stacco da terra", "COMPOUND", ["BACK", "HAMSTRINGS", "GLUTES", "CORE"], "BACK", ["BARBELL"], 5, ["stacco", "conventional deadlift"]),
  e("Sumo Deadlift", "Stacco sumo", "COMPOUND", ["BACK", "GLUTES", "QUADS"], "BACK", ["BARBELL"], 4),
  e("Trap Bar Deadlift", "Stacco con trap bar", "COMPOUND", ["BACK", "QUADS", "GLUTES"], "BACK", ["TRAP_BAR"], 3),
  e("Deficit Deadlift", "Stacco da deficit", "COMPOUND", ["BACK", "HAMSTRINGS", "GLUTES"], "BACK", ["BARBELL"], 5),
  e("Rack Pull", "Rack pull (stacco dai blocchi)", "COMPOUND", ["BACK", "GLUTES"], "BACK", ["BARBELL"], 3),
  e("Snatch-Grip Deadlift", "Stacco presa snatch", "COMPOUND", ["BACK", "HAMSTRINGS"], "BACK", ["BARBELL"], 4),
  e("Pull-Up", "Trazioni alla sbarra (presa prona)", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BODYWEIGHT"], 3, ["pullup", "trazioni"]),
  e("Chin-Up", "Trazioni presa supina", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BODYWEIGHT"], 3),
  e("Neutral-Grip Pull-Up", "Trazioni presa neutra", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BODYWEIGHT"], 3),
  e("Wide-Grip Pull-Up", "Trazioni presa larga", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BODYWEIGHT"], 4),
  e("Weighted Pull-Up", "Trazioni zavorrate", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BODYWEIGHT"], 4),
  e("Assisted Pull-Up Machine", "Trazioni assistite alla macchina", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["MACHINE"], 1),
  e("Band-Assisted Pull-Up", "Trazioni assistite con elastico", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BANDS"], 2),
  e("Archer Pull-Up", "Trazioni arciere", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BODYWEIGHT"], 5),
  e("Muscle-Up", "Muscle-up", "COMPOUND", ["BACK", "TRICEPS", "CHEST"], "BACK", ["BODYWEIGHT"], 5),
  e("Scapular Pull-Up", "Trazioni scapolari", "ISOLATION", ["BACK"], "BACK", ["BODYWEIGHT"], 1),
  e("Dead Hang", "Sospensione alla sbarra", "ISOLATION", ["BACK", "FOREARMS"], "BACK", ["BODYWEIGHT"], 1),
  e("Lat Pulldown", "Lat machine avanti", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["CABLE"], 1, ["lat machine", "pulldown"]),
  e("Wide-Grip Lat Pulldown", "Lat machine presa larga", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["CABLE"], 1),
  e("Close-Grip Lat Pulldown", "Lat machine presa stretta", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["CABLE"], 1),
  e("Reverse-Grip Lat Pulldown", "Lat machine presa supina", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["CABLE"], 1),
  e("Single-Arm Lat Pulldown", "Lat machine monobraccio", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["CABLE"], 2),
  e("Straight-Arm Pulldown", "Pullover al cavo a braccia tese", "ISOLATION", ["BACK"], "BACK", ["CABLE"], 2),
  e("Barbell Row", "Rematore con bilanciere", "COMPOUND", ["BACK", "BICEPS", "CORE"], "BACK", ["BARBELL"], 4, ["bent over row", "rematore"]),
  e("Pendlay Row", "Pendlay row", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BARBELL"], 4),
  e("Reverse-Grip Barbell Row", "Rematore presa supina", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BARBELL"], 3),
  e("Yates Row", "Yates row", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BARBELL"], 3),
  e("Dumbbell Row", "Rematore con manubrio", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["DUMBBELL"], 2, ["one arm row", "rematore manubrio"]),
  e("Chest-Supported Dumbbell Row", "Rematore con appoggio al petto", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["DUMBBELL"], 2),
  e("Incline Bench Dumbbell Row", "Rematore su panca inclinata", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["DUMBBELL"], 2),
  e("Seated Cable Row", "Pulley basso (rematore al cavo)", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["CABLE"], 2, ["pulley", "rematore cavo"]),
  e("Single-Arm Cable Row", "Pulley monobraccio", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["CABLE"], 2),
  e("Wide-Grip Cable Row", "Pulley presa larga", "COMPOUND", ["BACK", "SHOULDERS"], "BACK", ["CABLE"], 2),
  e("T-Bar Row", "Rematore T-bar", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BARBELL"], 3),
  e("Chest-Supported T-Bar Row", "T-bar row con appoggio", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["MACHINE"], 2),
  e("Machine Row", "Rematore alla macchina", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["MACHINE"], 1),
  e("Hammer Strength High Row", "High row Hammer", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["MACHINE"], 2),
  e("Meadows Row", "Meadows row", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BARBELL"], 3),
  e("Seal Row", "Seal row", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BARBELL"], 3),
  e("Inverted Row", "Rematore australiano", "COMPOUND", ["BACK", "BICEPS", "CORE"], "BACK", ["BODYWEIGHT"], 2, ["australian pull-up"]),
  e("Ring Row", "Rematore agli anelli", "COMPOUND", ["BACK", "BICEPS", "CORE"], "BACK", ["BODYWEIGHT"], 2),
  e("Renegade Row", "Renegade row", "COMPOUND", ["BACK", "CORE", "SHOULDERS"], "BACK", ["DUMBBELL"], 3),
  e("Kettlebell Row", "Rematore con kettlebell", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["KETTLEBELL"], 2),
  e("Smith Machine Row", "Rematore allo Smith", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["SMITH_MACHINE"], 2),
  e("Band Row", "Rematore con elastico", "COMPOUND", ["BACK", "BICEPS"], "BACK", ["BANDS"], 1),
  e("Back Extension", "Iperestensioni (lombari)", "ISOLATION", ["BACK", "GLUTES", "HAMSTRINGS"], "BACK", ["BODYWEIGHT"], 2, ["hyperextension", "lombari"]),
  e("45-Degree Back Extension", "Iperestensioni a 45°", "ISOLATION", ["BACK", "GLUTES"], "BACK", ["BODYWEIGHT"], 2),
  e("Reverse Hyperextension", "Reverse hyper", "ISOLATION", ["BACK", "GLUTES"], "BACK", ["MACHINE"], 2),
  e("Superman", "Superman a terra", "ISOLATION", ["BACK", "GLUTES"], "BACK", ["BODYWEIGHT"], 1),
  e("Good Morning", "Good morning", "COMPOUND", ["BACK", "HAMSTRINGS", "GLUTES"], "BACK", ["BARBELL"], 4),
  e("Barbell Shrug", "Scrollate con bilanciere", "ISOLATION", ["BACK", "SHOULDERS"], "BACK", ["BARBELL"], 1, ["shrug", "trapezi"]),
  e("Dumbbell Shrug", "Scrollate con manubri", "ISOLATION", ["BACK", "SHOULDERS"], "BACK", ["DUMBBELL"], 1),
  e("Cable Shrug", "Scrollate al cavo", "ISOLATION", ["BACK"], "BACK", ["CABLE"], 1),
  e("Trap Bar Shrug", "Scrollate con trap bar", "ISOLATION", ["BACK"], "BACK", ["TRAP_BAR"], 1),
  e("Smith Machine Shrug", "Scrollate allo Smith", "ISOLATION", ["BACK"], "BACK", ["SMITH_MACHINE"], 1),
  e("Rope Climb", "Salita alla fune", "COMPOUND", ["BACK", "BICEPS", "FOREARMS"], "BACK", ["BODYWEIGHT"], 4),

  // ─── SPALLE ─────────────────────────────────────────────────────────────────
  e("Overhead Press", "Lento avanti in piedi", "COMPOUND", ["SHOULDERS", "TRICEPS", "CORE"], "SHOULDERS", ["BARBELL"], 4, ["military press", "OHP", "lento avanti"]),
  e("Seated Barbell Shoulder Press", "Lento avanti da seduto", "COMPOUND", ["SHOULDERS", "TRICEPS"], "SHOULDERS", ["BARBELL"], 3),
  e("Behind-the-Neck Press", "Lento dietro", "COMPOUND", ["SHOULDERS", "TRICEPS"], "SHOULDERS", ["BARBELL"], 4),
  e("Dumbbell Shoulder Press", "Distensioni sopra la testa con manubri", "COMPOUND", ["SHOULDERS", "TRICEPS"], "SHOULDERS", ["DUMBBELL"], 2, ["shoulder press manubri"]),
  e("Seated Dumbbell Press", "Distensioni con manubri da seduto", "COMPOUND", ["SHOULDERS", "TRICEPS"], "SHOULDERS", ["DUMBBELL"], 2),
  e("Arnold Press", "Arnold press", "COMPOUND", ["SHOULDERS", "TRICEPS"], "SHOULDERS", ["DUMBBELL"], 3),
  e("Single-Arm Dumbbell Press", "Distensioni monobraccio con manubrio", "COMPOUND", ["SHOULDERS", "CORE"], "SHOULDERS", ["DUMBBELL"], 3),
  e("Machine Shoulder Press", "Shoulder press alla macchina", "COMPOUND", ["SHOULDERS", "TRICEPS"], "SHOULDERS", ["MACHINE"], 1),
  e("Smith Machine Shoulder Press", "Lento avanti allo Smith", "COMPOUND", ["SHOULDERS", "TRICEPS"], "SHOULDERS", ["SMITH_MACHINE"], 2),
  e("Cable Shoulder Press", "Distensioni sopra la testa ai cavi", "COMPOUND", ["SHOULDERS", "TRICEPS"], "SHOULDERS", ["CABLE"], 2),
  e("Push Press", "Push press", "COMPOUND", ["SHOULDERS", "TRICEPS", "QUADS"], "SHOULDERS", ["BARBELL"], 4),
  e("Kettlebell Military Press", "Military press con kettlebell", "COMPOUND", ["SHOULDERS", "TRICEPS", "CORE"], "SHOULDERS", ["KETTLEBELL"], 3),
  e("Kettlebell Push Press", "Push press con kettlebell", "COMPOUND", ["SHOULDERS", "QUADS"], "SHOULDERS", ["KETTLEBELL"], 3),
  e("Bottoms-Up Kettlebell Press", "Bottoms-up press con kettlebell", "COMPOUND", ["SHOULDERS", "CORE", "FOREARMS"], "SHOULDERS", ["KETTLEBELL"], 4),
  e("Handstand Push-Up", "Piegamenti in verticale", "COMPOUND", ["SHOULDERS", "TRICEPS", "CORE"], "SHOULDERS", ["BODYWEIGHT"], 5, ["HSPU"]),
  e("Pike Push-Up", "Piegamenti a pike", "COMPOUND", ["SHOULDERS", "TRICEPS"], "SHOULDERS", ["BODYWEIGHT"], 3),
  e("Landmine Shoulder Press", "Landmine press per spalle", "COMPOUND", ["SHOULDERS", "CORE"], "SHOULDERS", ["BARBELL"], 2),
  e("Z Press", "Z press", "COMPOUND", ["SHOULDERS", "CORE"], "SHOULDERS", ["BARBELL"], 4),
  e("Lateral Raise", "Alzate laterali con manubri", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["DUMBBELL"], 1, ["alzate laterali", "side raise"]),
  e("Cable Lateral Raise", "Alzate laterali ai cavi", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["CABLE"], 2),
  e("Machine Lateral Raise", "Alzate laterali alla macchina", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["MACHINE"], 1),
  e("Leaning Lateral Raise", "Alzate laterali inclinato", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["DUMBBELL"], 2),
  e("Lying Side Lateral Raise", "Alzate laterali su panca laterale", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["DUMBBELL"], 2),
  e("Band Lateral Raise", "Alzate laterali con elastico", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["BANDS"], 1),
  e("Front Raise", "Alzate frontali con manubri", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["DUMBBELL"], 1, ["alzate frontali"]),
  e("Barbell Front Raise", "Alzate frontali con bilanciere", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["BARBELL"], 1),
  e("Plate Front Raise", "Alzate frontali con disco", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["OTHER"], 1),
  e("Cable Front Raise", "Alzate frontali al cavo", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["CABLE"], 1),
  e("Rear Delt Fly", "Alzate posteriori (deltoide posteriore)", "ISOLATION", ["SHOULDERS", "BACK"], "SHOULDERS", ["DUMBBELL"], 1, ["reverse fly", "alzate a 90 gradi"]),
  e("Cable Rear Delt Fly", "Alzate posteriori ai cavi", "ISOLATION", ["SHOULDERS", "BACK"], "SHOULDERS", ["CABLE"], 2),
  e("Reverse Pec Deck", "Pectoral machine inversa", "ISOLATION", ["SHOULDERS", "BACK"], "SHOULDERS", ["MACHINE"], 1),
  e("Face Pull", "Face pull", "ISOLATION", ["SHOULDERS", "BACK"], "SHOULDERS", ["CABLE"], 2),
  e("Band Pull-Apart", "Aperture con elastico", "ISOLATION", ["SHOULDERS", "BACK"], "SHOULDERS", ["BANDS"], 1),
  e("Upright Row", "Tirate al mento con bilanciere", "COMPOUND", ["SHOULDERS", "BACK"], "SHOULDERS", ["BARBELL"], 2, ["tirate al mento"]),
  e("Cable Upright Row", "Tirate al mento al cavo", "COMPOUND", ["SHOULDERS", "BACK"], "SHOULDERS", ["CABLE"], 2),
  e("Dumbbell Upright Row", "Tirate al mento con manubri", "COMPOUND", ["SHOULDERS", "BACK"], "SHOULDERS", ["DUMBBELL"], 2),
  e("Dumbbell Scaption", "Alzate sul piano scapolare", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["DUMBBELL"], 1),
  e("Cuban Press", "Cuban press", "COMPOUND", ["SHOULDERS"], "SHOULDERS", ["DUMBBELL"], 3),
  e("External Rotation", "Rotazioni esterne (cuffia dei rotatori)", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["CABLE"], 1),
  e("Internal Rotation", "Rotazioni interne", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["CABLE"], 1),
  e("Band External Rotation", "Rotazioni esterne con elastico", "ISOLATION", ["SHOULDERS"], "SHOULDERS", ["BANDS"], 1),
  e("Kettlebell Halo", "Halo con kettlebell", "ISOLATION", ["SHOULDERS", "CORE"], "SHOULDERS", ["KETTLEBELL"], 2),
  e("Battle Ropes", "Battle rope (corde ondulatorie)", "CARDIO", ["SHOULDERS", "CORE", "FULL_BODY"], "SHOULDERS", ["OTHER"], 3),

  // ─── BICIPITI ───────────────────────────────────────────────────────────────
  e("Barbell Curl", "Curl con bilanciere", "ISOLATION", ["BICEPS"], "BICEPS", ["BARBELL"], 2, ["curl bilanciere"]),
  e("EZ-Bar Curl", "Curl con bilanciere EZ", "ISOLATION", ["BICEPS"], "BICEPS", ["BARBELL"], 2),
  e("Close-Grip Barbell Curl", "Curl presa stretta", "ISOLATION", ["BICEPS"], "BICEPS", ["BARBELL"], 2),
  e("Wide-Grip Barbell Curl", "Curl presa larga", "ISOLATION", ["BICEPS"], "BICEPS", ["BARBELL"], 2),
  e("Dumbbell Curl", "Curl con manubri", "ISOLATION", ["BICEPS"], "BICEPS", ["DUMBBELL"], 1, ["curl manubri"]),
  e("Alternating Dumbbell Curl", "Curl alternato con manubri", "ISOLATION", ["BICEPS"], "BICEPS", ["DUMBBELL"], 1),
  e("Hammer Curl", "Curl a martello", "ISOLATION", ["BICEPS", "FOREARMS"], "BICEPS", ["DUMBBELL"], 1, ["curl martello"]),
  e("Cross-Body Hammer Curl", "Curl a martello incrociato", "ISOLATION", ["BICEPS", "FOREARMS"], "BICEPS", ["DUMBBELL"], 1),
  e("Incline Dumbbell Curl", "Curl su panca inclinata", "ISOLATION", ["BICEPS"], "BICEPS", ["DUMBBELL"], 2),
  e("Concentration Curl", "Curl di concentrazione", "ISOLATION", ["BICEPS"], "BICEPS", ["DUMBBELL"], 1),
  e("Preacher Curl", "Curl alla panca Scott", "ISOLATION", ["BICEPS"], "BICEPS", ["BARBELL"], 2, ["scott curl", "panca scott"]),
  e("Dumbbell Preacher Curl", "Curl Scott con manubrio", "ISOLATION", ["BICEPS"], "BICEPS", ["DUMBBELL"], 2),
  e("Machine Preacher Curl", "Curl Scott alla macchina", "ISOLATION", ["BICEPS"], "BICEPS", ["MACHINE"], 1),
  e("Spider Curl", "Spider curl", "ISOLATION", ["BICEPS"], "BICEPS", ["DUMBBELL"], 2),
  e("Cable Curl", "Curl ai cavi", "ISOLATION", ["BICEPS"], "BICEPS", ["CABLE"], 1),
  e("Cable Hammer Curl (Rope)", "Curl a martello con corda", "ISOLATION", ["BICEPS", "FOREARMS"], "BICEPS", ["CABLE"], 1),
  e("High Cable Curl", "Curl ai cavi alti", "ISOLATION", ["BICEPS"], "BICEPS", ["CABLE"], 2),
  e("Drag Curl", "Drag curl", "ISOLATION", ["BICEPS"], "BICEPS", ["BARBELL"], 2),
  e("Zottman Curl", "Curl Zottman", "ISOLATION", ["BICEPS", "FOREARMS"], "BICEPS", ["DUMBBELL"], 2),
  e("Reverse Curl", "Curl inverso (presa prona)", "ISOLATION", ["BICEPS", "FOREARMS"], "BICEPS", ["BARBELL"], 2),
  e("Machine Biceps Curl", "Curl alla macchina", "ISOLATION", ["BICEPS"], "BICEPS", ["MACHINE"], 1),
  e("Band Curl", "Curl con elastico", "ISOLATION", ["BICEPS"], "BICEPS", ["BANDS"], 1),
  e("Bayesian Curl", "Curl bayesiano al cavo", "ISOLATION", ["BICEPS"], "BICEPS", ["CABLE"], 2),
  e("21s Biceps Curl", "Curl 21", "ISOLATION", ["BICEPS"], "BICEPS", ["BARBELL"], 2),

  // ─── TRICIPITI ──────────────────────────────────────────────────────────────
  e("Close-Grip Bench Press", "Panca presa stretta", "COMPOUND", ["TRICEPS", "CHEST"], "TRICEPS", ["BARBELL"], 3),
  e("Triceps Dip", "Dip per tricipiti", "COMPOUND", ["TRICEPS", "CHEST"], "TRICEPS", ["BODYWEIGHT"], 3),
  e("Bench Dip", "Dip tra due panche", "COMPOUND", ["TRICEPS"], "TRICEPS", ["BODYWEIGHT"], 2),
  e("Ring Dip", "Dip agli anelli", "COMPOUND", ["TRICEPS", "CHEST"], "TRICEPS", ["BODYWEIGHT"], 4),
  e("Diamond Push-Up", "Piegamenti a diamante", "COMPOUND", ["TRICEPS", "CHEST"], "TRICEPS", ["BODYWEIGHT"], 3),
  e("Triceps Pushdown", "Push down ai cavi", "ISOLATION", ["TRICEPS"], "TRICEPS", ["CABLE"], 1, ["pushdown"]),
  e("Rope Pushdown", "Push down con corda", "ISOLATION", ["TRICEPS"], "TRICEPS", ["CABLE"], 1),
  e("V-Bar Pushdown", "Push down con V-bar", "ISOLATION", ["TRICEPS"], "TRICEPS", ["CABLE"], 1),
  e("Reverse-Grip Pushdown", "Push down presa supina", "ISOLATION", ["TRICEPS"], "TRICEPS", ["CABLE"], 1),
  e("Single-Arm Pushdown", "Push down monobraccio", "ISOLATION", ["TRICEPS"], "TRICEPS", ["CABLE"], 1),
  e("Overhead Cable Triceps Extension", "French press ai cavi sopra la testa", "ISOLATION", ["TRICEPS"], "TRICEPS", ["CABLE"], 2),
  e("EZ-Bar Skullcrusher", "French press su panca (skullcrusher)", "ISOLATION", ["TRICEPS"], "TRICEPS", ["BARBELL"], 3, ["skull crusher", "french press"]),
  e("Dumbbell Skullcrusher", "Skullcrusher con manubri", "ISOLATION", ["TRICEPS"], "TRICEPS", ["DUMBBELL"], 2),
  e("Overhead Dumbbell Extension", "Estensioni sopra la testa con manubrio", "ISOLATION", ["TRICEPS"], "TRICEPS", ["DUMBBELL"], 2),
  e("Single-Arm Overhead Extension", "Estensione sopra la testa monobraccio", "ISOLATION", ["TRICEPS"], "TRICEPS", ["DUMBBELL"], 2),
  e("Triceps Kickback", "Kickback per tricipiti", "ISOLATION", ["TRICEPS"], "TRICEPS", ["DUMBBELL"], 1),
  e("Cable Kickback", "Kickback ai cavi", "ISOLATION", ["TRICEPS"], "TRICEPS", ["CABLE"], 1),
  e("JM Press", "JM press", "COMPOUND", ["TRICEPS", "CHEST"], "TRICEPS", ["BARBELL"], 4),
  e("Tate Press", "Tate press", "ISOLATION", ["TRICEPS"], "TRICEPS", ["DUMBBELL"], 3),
  e("Machine Triceps Extension", "Estensioni tricipiti alla macchina", "ISOLATION", ["TRICEPS"], "TRICEPS", ["MACHINE"], 1),
  e("Band Triceps Extension", "Estensioni tricipiti con elastico", "ISOLATION", ["TRICEPS"], "TRICEPS", ["BANDS"], 1),
  e("Board Press", "Board press", "COMPOUND", ["TRICEPS", "CHEST"], "TRICEPS", ["BARBELL"], 4),

  // ─── AVAMBRACCI / PRESA ─────────────────────────────────────────────────────
  e("Barbell Wrist Curl", "Curl ai polsi con bilanciere", "ISOLATION", ["FOREARMS"], "FOREARMS", ["BARBELL"], 1),
  e("Reverse Wrist Curl", "Curl inverso ai polsi", "ISOLATION", ["FOREARMS"], "FOREARMS", ["BARBELL"], 1),
  e("Dumbbell Wrist Curl", "Curl ai polsi con manubri", "ISOLATION", ["FOREARMS"], "FOREARMS", ["DUMBBELL"], 1),
  e("Cable Wrist Curl", "Curl ai polsi al cavo", "ISOLATION", ["FOREARMS"], "FOREARMS", ["CABLE"], 1),
  e("Farmer's Walk", "Farmer's walk (camminata del contadino)", "COMPOUND", ["FOREARMS", "CORE", "FULL_BODY"], "FOREARMS", ["DUMBBELL"], 3),
  e("Plate Pinch Hold", "Pinch grip con dischi", "ISOLATION", ["FOREARMS"], "FOREARMS", ["OTHER"], 2),
  e("Wrist Roller", "Wrist roller (arrotolatore da polso)", "ISOLATION", ["FOREARMS"], "FOREARMS", ["OTHER"], 2),
  e("Finger Curl", "Curl delle dita", "ISOLATION", ["FOREARMS"], "FOREARMS", ["BARBELL"], 1),
  e("Towel Hang", "Sospensione con asciugamano", "ISOLATION", ["FOREARMS", "BACK"], "FOREARMS", ["BODYWEIGHT"], 3),

  // ─── QUADRICIPITI ───────────────────────────────────────────────────────────
  e("Back Squat", "Squat con bilanciere", "COMPOUND", ["QUADS", "GLUTES", "CORE"], "QUADS", ["BARBELL"], 4, ["squat", "barbell squat"]),
  e("High-Bar Back Squat", "Squat high bar", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["BARBELL"], 4),
  e("Low-Bar Back Squat", "Squat low bar", "COMPOUND", ["QUADS", "GLUTES", "BACK"], "QUADS", ["BARBELL"], 4),
  e("Front Squat", "Front squat (squat frontale)", "COMPOUND", ["QUADS", "CORE"], "QUADS", ["BARBELL"], 4),
  e("Zercher Squat", "Zercher squat", "COMPOUND", ["QUADS", "CORE", "GLUTES"], "QUADS", ["BARBELL"], 4),
  e("Overhead Squat", "Overhead squat", "COMPOUND", ["QUADS", "SHOULDERS", "CORE"], "QUADS", ["BARBELL"], 5),
  e("Box Squat", "Box squat", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["BARBELL"], 3),
  e("Pause Squat", "Squat con fermo", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["BARBELL"], 4),
  e("Safety Bar Squat", "Squat con safety bar", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["BARBELL"], 4),
  e("Smith Machine Squat", "Squat allo Smith", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["SMITH_MACHINE"], 2),
  e("Hack Squat Machine", "Hack squat alla macchina", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["MACHINE"], 2),
  e("Barbell Hack Squat", "Hack squat con bilanciere", "COMPOUND", ["QUADS"], "QUADS", ["BARBELL"], 3),
  e("Pendulum Squat", "Pendulum squat", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["MACHINE"], 2),
  e("Leg Press", "Pressa per gambe", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["MACHINE"], 2, ["pressa"]),
  e("Single-Leg Press", "Pressa monopodalica", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["MACHINE"], 2),
  e("Narrow-Stance Leg Press", "Pressa a stance stretta", "COMPOUND", ["QUADS"], "QUADS", ["MACHINE"], 2),
  e("Goblet Squat", "Goblet squat", "COMPOUND", ["QUADS", "GLUTES", "CORE"], "QUADS", ["DUMBBELL"], 2),
  e("Dumbbell Squat", "Squat con manubri", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["DUMBBELL"], 2),
  e("Bodyweight Squat", "Squat a corpo libero", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["BODYWEIGHT"], 1),
  e("Jump Squat", "Squat con salto", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["BODYWEIGHT"], 3),
  e("Pistol Squat", "Pistol squat (squat su una gamba)", "COMPOUND", ["QUADS", "GLUTES", "CORE"], "QUADS", ["BODYWEIGHT"], 5),
  e("Sissy Squat", "Sissy squat", "ISOLATION", ["QUADS"], "QUADS", ["BODYWEIGHT"], 3),
  e("Wall Sit", "Sedia al muro (isometria)", "ISOLATION", ["QUADS"], "QUADS", ["BODYWEIGHT"], 2),
  e("Bulgarian Split Squat", "Affondo bulgaro", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["DUMBBELL"], 3, ["split squat bulgaro"]),
  e("Barbell Split Squat", "Split squat con bilanciere", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["BARBELL"], 3),
  e("Walking Lunge", "Affondi camminati", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["DUMBBELL"], 2, ["affondi"]),
  e("Barbell Lunge", "Affondi con bilanciere", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["BARBELL"], 3),
  e("Reverse Lunge", "Affondi indietro", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["DUMBBELL"], 2),
  e("Lateral Lunge", "Affondi laterali", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["DUMBBELL"], 2),
  e("Curtsy Lunge", "Affondo incrociato", "COMPOUND", ["GLUTES", "QUADS"], "GLUTES", ["DUMBBELL"], 2),
  e("Step-Up", "Step-up su rialzo", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["DUMBBELL"], 2),
  e("Lateral Step-Up", "Step-up laterale", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["DUMBBELL"], 2),
  e("Leg Extension", "Leg extension", "ISOLATION", ["QUADS"], "QUADS", ["MACHINE"], 1),
  e("Single-Leg Extension", "Leg extension monopodalica", "ISOLATION", ["QUADS"], "QUADS", ["MACHINE"], 1),
  e("Belt Squat", "Belt squat", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["MACHINE"], 2),
  e("Landmine Squat", "Landmine squat", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["BARBELL"], 2),
  e("Cyclist Squat", "Squat da ciclista (talloni rialzati)", "COMPOUND", ["QUADS"], "QUADS", ["BARBELL"], 3),

  // ─── FEMORALI ───────────────────────────────────────────────────────────────
  e("Romanian Deadlift", "Stacco rumeno", "COMPOUND", ["HAMSTRINGS", "GLUTES", "BACK"], "HAMSTRINGS", ["BARBELL"], 3, ["RDL", "stacco rumeno"]),
  e("Dumbbell Romanian Deadlift", "Stacco rumeno con manubri", "COMPOUND", ["HAMSTRINGS", "GLUTES"], "HAMSTRINGS", ["DUMBBELL"], 2),
  e("Single-Leg Romanian Deadlift", "Stacco rumeno monopodalico", "COMPOUND", ["HAMSTRINGS", "GLUTES", "CORE"], "HAMSTRINGS", ["DUMBBELL"], 3),
  e("Stiff-Legged Deadlift", "Stacco a gambe tese", "COMPOUND", ["HAMSTRINGS", "GLUTES", "BACK"], "HAMSTRINGS", ["BARBELL"], 3),
  e("Lying Leg Curl", "Leg curl da sdraiato", "ISOLATION", ["HAMSTRINGS"], "HAMSTRINGS", ["MACHINE"], 1),
  e("Seated Leg Curl", "Leg curl da seduto", "ISOLATION", ["HAMSTRINGS"], "HAMSTRINGS", ["MACHINE"], 1),
  e("Standing Leg Curl", "Leg curl in piedi", "ISOLATION", ["HAMSTRINGS"], "HAMSTRINGS", ["MACHINE"], 1),
  e("Nordic Hamstring Curl", "Nordic curl", "ISOLATION", ["HAMSTRINGS"], "HAMSTRINGS", ["BODYWEIGHT"], 5),
  e("Glute-Ham Raise", "Glute-ham raise", "COMPOUND", ["HAMSTRINGS", "GLUTES"], "HAMSTRINGS", ["MACHINE"], 4),
  e("Swiss Ball Leg Curl", "Leg curl con fitball", "ISOLATION", ["HAMSTRINGS", "GLUTES"], "HAMSTRINGS", ["OTHER"], 2),
  e("Slider Leg Curl", "Leg curl con slider", "ISOLATION", ["HAMSTRINGS", "GLUTES"], "HAMSTRINGS", ["OTHER"], 3),
  e("Cable Pull-Through", "Pull-through al cavo", "COMPOUND", ["HAMSTRINGS", "GLUTES"], "HAMSTRINGS", ["CABLE"], 2),
  e("Kettlebell Swing", "Swing con kettlebell", "COMPOUND", ["HAMSTRINGS", "GLUTES", "CORE"], "HAMSTRINGS", ["KETTLEBELL"], 3, ["swing"]),
  e("Single-Arm Kettlebell Swing", "Swing monobraccio", "COMPOUND", ["HAMSTRINGS", "GLUTES", "CORE"], "HAMSTRINGS", ["KETTLEBELL"], 3),
  e("Band Leg Curl", "Leg curl con elastico", "ISOLATION", ["HAMSTRINGS"], "HAMSTRINGS", ["BANDS"], 1),

  // ─── GLUTEI ─────────────────────────────────────────────────────────────────
  e("Barbell Hip Thrust", "Hip thrust con bilanciere", "COMPOUND", ["GLUTES", "HAMSTRINGS"], "GLUTES", ["BARBELL"], 2, ["hip thrust"]),
  e("Machine Hip Thrust", "Hip thrust alla macchina", "COMPOUND", ["GLUTES"], "GLUTES", ["MACHINE"], 1),
  e("Single-Leg Hip Thrust", "Hip thrust monopodalico", "COMPOUND", ["GLUTES"], "GLUTES", ["BODYWEIGHT"], 3),
  e("Glute Bridge", "Ponte per glutei", "COMPOUND", ["GLUTES", "HAMSTRINGS"], "GLUTES", ["BODYWEIGHT"], 1),
  e("Barbell Glute Bridge", "Ponte glutei con bilanciere", "COMPOUND", ["GLUTES"], "GLUTES", ["BARBELL"], 2),
  e("Cable Glute Kickback", "Slancio glutei al cavo", "ISOLATION", ["GLUTES"], "GLUTES", ["CABLE"], 1),
  e("Machine Glute Kickback", "Slancio glutei alla macchina", "ISOLATION", ["GLUTES"], "GLUTES", ["MACHINE"], 1),
  e("Donkey Kick", "Slancio a quadrupedia", "ISOLATION", ["GLUTES"], "GLUTES", ["BODYWEIGHT"], 1),
  e("Fire Hydrant", "Fire hydrant", "ISOLATION", ["GLUTES"], "GLUTES", ["BODYWEIGHT"], 1),
  e("Hip Abduction Machine", "Abduzione anche alla macchina", "ISOLATION", ["GLUTES"], "GLUTES", ["MACHINE"], 1),
  e("Hip Adduction Machine", "Adduzione anche alla macchina", "ISOLATION", ["GLUTES", "QUADS"], "GLUTES", ["MACHINE"], 1),
  e("Band Hip Abduction", "Abduzione con elastico", "ISOLATION", ["GLUTES"], "GLUTES", ["BANDS"], 1),
  e("Lateral Band Walk", "Camminata laterale con elastico", "ISOLATION", ["GLUTES"], "GLUTES", ["BANDS"], 1, ["monster walk"]),
  e("Frog Pump", "Frog pump", "ISOLATION", ["GLUTES"], "GLUTES", ["BODYWEIGHT"], 1),
  e("Sumo Squat", "Squat sumo", "COMPOUND", ["GLUTES", "QUADS"], "GLUTES", ["DUMBBELL"], 2),
  e("Kettlebell Deadlift", "Stacco con kettlebell", "COMPOUND", ["GLUTES", "HAMSTRINGS", "BACK"], "GLUTES", ["KETTLEBELL"], 2),

  // ─── POLPACCI ───────────────────────────────────────────────────────────────
  e("Standing Calf Raise", "Calf raise in piedi", "ISOLATION", ["CALVES"], "CALVES", ["MACHINE"], 1, ["calf in piedi"]),
  e("Seated Calf Raise", "Calf raise da seduto", "ISOLATION", ["CALVES"], "CALVES", ["MACHINE"], 1),
  e("Barbell Calf Raise", "Calf raise con bilanciere", "ISOLATION", ["CALVES"], "CALVES", ["BARBELL"], 1),
  e("Dumbbell Calf Raise", "Calf raise con manubri", "ISOLATION", ["CALVES"], "CALVES", ["DUMBBELL"], 1),
  e("Leg Press Calf Raise", "Calf raise alla pressa", "ISOLATION", ["CALVES"], "CALVES", ["MACHINE"], 1),
  e("Donkey Calf Raise", "Donkey calf raise", "ISOLATION", ["CALVES"], "CALVES", ["MACHINE"], 2),
  e("Smith Machine Calf Raise", "Calf raise allo Smith", "ISOLATION", ["CALVES"], "CALVES", ["SMITH_MACHINE"], 1),
  e("Single-Leg Calf Raise", "Calf raise monopodalico", "ISOLATION", ["CALVES"], "CALVES", ["BODYWEIGHT"], 2),
  e("Tibialis Raise", "Tibialis raise", "ISOLATION", ["CALVES"], "CALVES", ["BODYWEIGHT"], 1),
  e("Jump Rope Calf Bounce", "Rimbalzi sui polpacci con corda", "CARDIO", ["CALVES"], "CALVES", ["OTHER"], 2),

  // ─── CORE / ADDOME ──────────────────────────────────────────────────────────
  e("Plank", "Plank", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 1, ["plancia"]),
  e("Side Plank", "Plank laterale", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 2),
  e("Weighted Plank", "Plank zavorrato", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 3),
  e("Crunch", "Crunch", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 1),
  e("Cable Crunch", "Crunch ai cavi", "ISOLATION", ["CORE"], "CORE", ["CABLE"], 2),
  e("Machine Crunch", "Crunch alla macchina", "ISOLATION", ["CORE"], "CORE", ["MACHINE"], 1),
  e("Decline Crunch", "Crunch su panca declinata", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 2),
  e("Reverse Crunch", "Crunch inverso", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 2),
  e("Bicycle Crunch", "Crunch bicicletta", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 1),
  e("Sit-Up", "Sit-up", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 1),
  e("Weighted Sit-Up", "Sit-up zavorrato", "ISOLATION", ["CORE"], "CORE", ["OTHER"], 2),
  e("V-Up", "V-up", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 3),
  e("Hanging Leg Raise", "Sollevamento gambe alla sbarra", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 4),
  e("Hanging Knee Raise", "Sollevamento ginocchia alla sbarra", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 2),
  e("Captain's Chair Knee Raise", "Sollevamento ginocchia alle parallele", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 2),
  e("Toes-to-Bar", "Toes to bar", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 4),
  e("Lying Leg Raise", "Sollevamento gambe da terra", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 2),
  e("Flutter Kick", "Forbici a terra", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 1),
  e("Russian Twist", "Russian twist", "ISOLATION", ["CORE"], "CORE", ["OTHER"], 2),
  e("Cable Woodchop", "Woodchop al cavo", "ISOLATION", ["CORE"], "CORE", ["CABLE"], 2),
  e("Pallof Press", "Pallof press", "ISOLATION", ["CORE"], "CORE", ["CABLE"], 2),
  e("Ab Wheel Rollout", "Rollout con ruota", "COMPOUND", ["CORE"], "CORE", ["OTHER"], 4),
  e("Barbell Rollout", "Rollout con bilanciere", "COMPOUND", ["CORE"], "CORE", ["BARBELL"], 4),
  e("Dead Bug", "Dead bug", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 1),
  e("Bird Dog", "Bird dog", "ISOLATION", ["CORE", "BACK"], "CORE", ["BODYWEIGHT"], 1),
  e("Hollow Body Hold", "Hollow body hold", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 3),
  e("Mountain Climber", "Mountain climber", "CARDIO", ["CORE", "FULL_BODY"], "CORE", ["BODYWEIGHT"], 2),
  e("Dragon Flag", "Dragon flag", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 5),
  e("L-Sit", "L-sit", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 4),
  e("Dumbbell Side Bend", "Flessioni laterali con manubrio", "ISOLATION", ["CORE"], "CORE", ["DUMBBELL"], 1),
  e("Oblique Crunch", "Crunch obliqui", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 1),
  e("Suitcase Carry", "Suitcase carry", "COMPOUND", ["CORE", "FOREARMS"], "CORE", ["DUMBBELL"], 2),
  e("Copenhagen Plank", "Plank di Copenhagen", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 4),
  e("Stomach Vacuum", "Vacuum addominale", "ISOLATION", ["CORE"], "CORE", ["BODYWEIGHT"], 2),
  e("Medicine Ball Slam", "Slam con palla medica", "CARDIO", ["CORE", "FULL_BODY"], "CORE", ["OTHER"], 2),

  // ─── OLIMPICI / POWERLIFTING / FULL BODY ────────────────────────────────────
  e("Power Clean", "Power clean (girata di potenza)", "COMPOUND", ["FULL_BODY", "HAMSTRINGS", "SHOULDERS"], "FULL_BODY", ["BARBELL"], 5),
  e("Hang Clean", "Hang clean", "COMPOUND", ["FULL_BODY", "HAMSTRINGS"], "FULL_BODY", ["BARBELL"], 5),
  e("Clean", "Girata (clean)", "COMPOUND", ["FULL_BODY", "QUADS"], "FULL_BODY", ["BARBELL"], 5),
  e("Clean and Jerk", "Slancio (clean and jerk)", "COMPOUND", ["FULL_BODY", "SHOULDERS"], "FULL_BODY", ["BARBELL"], 5),
  e("Clean and Press", "Girata e spinta", "COMPOUND", ["FULL_BODY", "SHOULDERS"], "FULL_BODY", ["BARBELL"], 4),
  e("Snatch", "Strappo (snatch)", "COMPOUND", ["FULL_BODY", "SHOULDERS"], "FULL_BODY", ["BARBELL"], 5),
  e("Power Snatch", "Power snatch", "COMPOUND", ["FULL_BODY", "SHOULDERS"], "FULL_BODY", ["BARBELL"], 5),
  e("Hang Snatch", "Hang snatch", "COMPOUND", ["FULL_BODY", "SHOULDERS"], "FULL_BODY", ["BARBELL"], 5),
  e("Split Jerk", "Split jerk", "COMPOUND", ["SHOULDERS", "QUADS", "FULL_BODY"], "SHOULDERS", ["BARBELL"], 5),
  e("Clean Pull", "Clean pull", "COMPOUND", ["BACK", "HAMSTRINGS"], "BACK", ["BARBELL"], 4),
  e("Snatch Pull", "Snatch pull", "COMPOUND", ["BACK", "HAMSTRINGS"], "BACK", ["BARBELL"], 4),
  e("Clean High Pull", "Tirata alta", "COMPOUND", ["BACK", "SHOULDERS"], "BACK", ["BARBELL"], 4),
  e("Thruster", "Thruster", "COMPOUND", ["FULL_BODY", "QUADS", "SHOULDERS"], "FULL_BODY", ["BARBELL"], 4),
  e("Dumbbell Thruster", "Thruster con manubri", "COMPOUND", ["FULL_BODY", "SHOULDERS"], "FULL_BODY", ["DUMBBELL"], 3),
  e("Burpee", "Burpee", "CARDIO", ["FULL_BODY"], "FULL_BODY", ["BODYWEIGHT"], 3),
  e("Burpee Box Jump", "Burpee con salto sul box", "CARDIO", ["FULL_BODY", "QUADS"], "FULL_BODY", ["BODYWEIGHT"], 4),
  e("Box Jump", "Salto sul box", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["BODYWEIGHT"], 3),
  e("Broad Jump", "Salto in lungo da fermo", "COMPOUND", ["QUADS", "GLUTES"], "QUADS", ["BODYWEIGHT"], 3),
  e("Turkish Get-Up", "Turkish get-up", "COMPOUND", ["FULL_BODY", "CORE", "SHOULDERS"], "FULL_BODY", ["KETTLEBELL"], 4),
  e("Kettlebell Clean", "Clean con kettlebell", "COMPOUND", ["FULL_BODY", "SHOULDERS"], "FULL_BODY", ["KETTLEBELL"], 3),
  e("Kettlebell Snatch", "Snatch con kettlebell", "COMPOUND", ["FULL_BODY", "SHOULDERS"], "FULL_BODY", ["KETTLEBELL"], 4),
  e("Kettlebell Goblet Clean", "Goblet clean", "COMPOUND", ["FULL_BODY"], "FULL_BODY", ["KETTLEBELL"], 2),
  e("Kettlebell Windmill", "Windmill con kettlebell", "COMPOUND", ["CORE", "SHOULDERS"], "CORE", ["KETTLEBELL"], 4),
  e("Kettlebell Figure 8", "Figure 8 con kettlebell", "COMPOUND", ["CORE", "FULL_BODY"], "CORE", ["KETTLEBELL"], 2),
  e("Sled Push", "Spinta della slitta", "CARDIO", ["QUADS", "GLUTES", "FULL_BODY"], "QUADS", ["OTHER"], 3),
  e("Sled Drag", "Trascinamento slitta", "CARDIO", ["QUADS", "HAMSTRINGS"], "QUADS", ["OTHER"], 3),
  e("Prowler Sprint", "Sprint con prowler", "CARDIO", ["QUADS", "FULL_BODY"], "QUADS", ["OTHER"], 4),
  e("Tire Flip", "Ribaltamento pneumatico", "COMPOUND", ["FULL_BODY", "BACK", "QUADS"], "FULL_BODY", ["OTHER"], 4),
  e("Atlas Stone Lift", "Sollevamento atlas stone", "COMPOUND", ["FULL_BODY", "BACK"], "FULL_BODY", ["OTHER"], 5),
  e("Log Press", "Log press", "COMPOUND", ["SHOULDERS", "TRICEPS"], "SHOULDERS", ["OTHER"], 4),
  e("Yoke Walk", "Yoke walk", "COMPOUND", ["FULL_BODY", "CORE"], "FULL_BODY", ["OTHER"], 4),
  e("Sandbag Carry", "Trasporto sandbag", "COMPOUND", ["FULL_BODY", "CORE"], "FULL_BODY", ["OTHER"], 3),
  e("Sledgehammer Swing", "Colpi di mazza sul pneumatico", "CARDIO", ["CORE", "FULL_BODY"], "CORE", ["OTHER"], 3),
  e("Bear Crawl", "Bear crawl", "CARDIO", ["FULL_BODY", "CORE"], "FULL_BODY", ["BODYWEIGHT"], 2),
  e("Wall Ball", "Wall ball", "CARDIO", ["FULL_BODY", "QUADS", "SHOULDERS"], "FULL_BODY", ["OTHER"], 3),
  e("Devil Press", "Devil press", "COMPOUND", ["FULL_BODY", "SHOULDERS"], "FULL_BODY", ["DUMBBELL"], 4),
  e("Man Maker", "Man maker", "COMPOUND", ["FULL_BODY"], "FULL_BODY", ["DUMBBELL"], 4),

  // ─── CARDIO / ENDURANCE ─────────────────────────────────────────────────────
  e("Running (Outdoor)", "Corsa all'aperto", "CARDIO", ["FULL_BODY", "QUADS"], "FULL_BODY", ["OTHER"], 2, ["corsa", "running"]),
  e("Treadmill Run", "Corsa sul tapis roulant", "CARDIO", ["FULL_BODY", "QUADS"], "FULL_BODY", ["MACHINE"], 2),
  e("Interval Sprints", "Sprint a intervalli", "CARDIO", ["QUADS", "HAMSTRINGS", "FULL_BODY"], "FULL_BODY", ["OTHER"], 4),
  e("Hill Sprints", "Sprint in salita", "CARDIO", ["QUADS", "GLUTES"], "QUADS", ["OTHER"], 4),
  e("Walking", "Camminata", "CARDIO", ["FULL_BODY"], "FULL_BODY", ["OTHER"], 1),
  e("Incline Treadmill Walk", "Camminata in salita al tapis roulant", "CARDIO", ["FULL_BODY", "GLUTES", "CALVES"], "FULL_BODY", ["MACHINE"], 2),
  e("Stationary Bike", "Cyclette", "CARDIO", ["QUADS", "FULL_BODY"], "QUADS", ["MACHINE"], 2),
  e("Spinning", "Spinning", "CARDIO", ["QUADS", "GLUTES"], "QUADS", ["MACHINE"], 3),
  e("Cycling (Outdoor)", "Ciclismo su strada", "CARDIO", ["QUADS", "GLUTES"], "QUADS", ["OTHER"], 3),
  e("Rowing Machine", "Vogatore", "CARDIO", ["FULL_BODY", "BACK"], "FULL_BODY", ["MACHINE"], 3, ["rower", "remoergometro"]),
  e("Elliptical Trainer", "Ellittica", "CARDIO", ["FULL_BODY"], "FULL_BODY", ["MACHINE"], 1),
  e("Stair Climber", "Stair climber (scalatore)", "CARDIO", ["GLUTES", "QUADS"], "GLUTES", ["MACHINE"], 2),
  e("Assault Bike", "Assault bike", "CARDIO", ["FULL_BODY"], "FULL_BODY", ["MACHINE"], 4),
  e("SkiErg", "SkiErg", "CARDIO", ["FULL_BODY", "BACK"], "FULL_BODY", ["MACHINE"], 3),
  e("Jump Rope", "Corda per saltare", "CARDIO", ["CALVES", "FULL_BODY"], "FULL_BODY", ["OTHER"], 2, ["salto della corda"]),
  e("Swimming", "Nuoto", "CARDIO", ["FULL_BODY", "BACK"], "FULL_BODY", ["OTHER"], 3),
  e("Boxing / Heavy Bag", "Boxe al sacco", "CARDIO", ["FULL_BODY", "SHOULDERS"], "FULL_BODY", ["OTHER"], 3),
  e("Shadow Boxing", "Shadow boxing", "CARDIO", ["FULL_BODY", "SHOULDERS"], "FULL_BODY", ["BODYWEIGHT"], 2),
  e("Hiking", "Escursionismo / trekking", "CARDIO", ["FULL_BODY", "QUADS", "GLUTES"], "FULL_BODY", ["OTHER"], 2),
  e("Padel / Tennis", "Padel / tennis", "CARDIO", ["FULL_BODY"], "FULL_BODY", ["OTHER"], 2),
  e("Football (Soccer)", "Calcio", "CARDIO", ["FULL_BODY", "QUADS"], "FULL_BODY", ["OTHER"], 2),
  e("Basketball", "Basket", "CARDIO", ["FULL_BODY", "QUADS"], "FULL_BODY", ["OTHER"], 2),

  // ─── MOBILITÀ / STRETCHING ──────────────────────────────────────────────────
  e("Cat-Cow Stretch", "Gatto-cammello", "STRETCHING", ["BACK", "CORE"], "BACK", ["BODYWEIGHT"], 1),
  e("Child's Pose", "Posizione del bambino", "STRETCHING", ["BACK"], "BACK", ["BODYWEIGHT"], 1),
  e("Cobra Stretch", "Allungamento del cobra", "STRETCHING", ["CORE", "BACK"], "CORE", ["BODYWEIGHT"], 1),
  e("Hamstring Stretch", "Allungamento femorali", "STRETCHING", ["HAMSTRINGS"], "HAMSTRINGS", ["BODYWEIGHT"], 1),
  e("Quad Stretch", "Allungamento quadricipiti", "STRETCHING", ["QUADS"], "QUADS", ["BODYWEIGHT"], 1),
  e("Hip Flexor Stretch", "Allungamento flessori dell'anca", "STRETCHING", ["QUADS", "GLUTES"], "QUADS", ["BODYWEIGHT"], 1),
  e("Pigeon Pose", "Posizione del piccione", "STRETCHING", ["GLUTES"], "GLUTES", ["BODYWEIGHT"], 2),
  e("Couch Stretch", "Couch stretch", "STRETCHING", ["QUADS"], "QUADS", ["BODYWEIGHT"], 2),
  e("Doorway Chest Stretch", "Allungamento pettorali sulla porta", "STRETCHING", ["CHEST"], "CHEST", ["BODYWEIGHT"], 1),
  e("Lat Stretch", "Allungamento dorsali", "STRETCHING", ["BACK"], "BACK", ["BODYWEIGHT"], 1),
  e("Shoulder Dislocates", "Circonduzioni con bastone/elastico", "STRETCHING", ["SHOULDERS"], "SHOULDERS", ["BANDS"], 1),
  e("Thoracic Spine Rotation", "Mobilità toracica in rotazione", "STRETCHING", ["BACK", "CORE"], "BACK", ["BODYWEIGHT"], 1),
  e("90/90 Hip Stretch", "Stretching anche 90/90", "STRETCHING", ["GLUTES"], "GLUTES", ["BODYWEIGHT"], 2),
  e("Calf Stretch", "Allungamento polpacci", "STRETCHING", ["CALVES"], "CALVES", ["BODYWEIGHT"], 1),
  e("World's Greatest Stretch", "World's greatest stretch", "STRETCHING", ["FULL_BODY"], "FULL_BODY", ["BODYWEIGHT"], 2),
  e("Foam Rolling", "Foam roller (auto-massaggio)", "STRETCHING", ["FULL_BODY"], "FULL_BODY", ["OTHER"], 1),
  e("Deep Squat Hold", "Tenuta in accosciata profonda", "STRETCHING", ["QUADS", "GLUTES"], "QUADS", ["BODYWEIGHT"], 2),
  e("Neck Stretch", "Allungamento del collo", "STRETCHING", ["FULL_BODY"], "FULL_BODY", ["BODYWEIGHT"], 1),
  e("Wrist Mobility", "Mobilità dei polsi", "STRETCHING", ["FOREARMS"], "FOREARMS", ["BODYWEIGHT"], 1),
  e("Ankle Mobility Drill", "Mobilità della caviglia", "STRETCHING", ["CALVES"], "CALVES", ["BODYWEIGHT"], 1),
];
